### PR TITLE
Design update

### LINKED ISSUE #443: wrong pip displayed
1.50 is displayed as 1.5

screen shot 2016-06-16 at 16 36 48

### PR DESCRIPTION
**Pull request by zeala**
Closes #443

### CODE REVIEW

File: src/client/src/ui/analytics/views/analyticsView.jsx [hunk 1]
```diff
@@ -106,41 +113,38 @@ export default class AnalyticsView extends ViewBase {
...
-    let positionsChartModel:PositionsChartModel = this.state.model.positionsChartModel;
-    let isPnL = positionsChartModel.basePnlDisplayModelSelected;
-    let baseClassName = 'btn analytics__buttons-tab-btn ';
-    let selectedClassName = `${baseClassName} analytics__buttons-tab-btn--selected`;
-    let pnlButtonClassName = isPnL ? selectedClassName : baseClassName;
-    let positionButtonClassName = isPnL ? baseClassName : selectedClassName;
+    return (
+        <div className='analytics__bubblechart-container'>
+          <span className='analytics__chart-title analytics__bubblechart-title'>Positions</span>
+          <PositionsBubbleChart data={positionsCharData}/>
```
Comment (fdore) [inline src/client/src/ui/analytics/views/analyticsView.jsx]: typo in positionsCharData

File: src/client/src/ui/analytics/views/analyticsView.jsx [hunk 2]
```diff
@@ -106,41 +113,38 @@ export default class AnalyticsView extends ViewBase {
...
           {pnlChart}
         </div>
       </div>
     );
   }
 
-  _createPositionsComponents() {
+  _createPositionsChart(){
+    let model:AnalyticsModel = this.state.model;
+    let positionsCharData = model.positionsChartModel.seriesData;
```
Comment (fdore) [inline src/client/src/ui/analytics/views/analyticsView.jsx]: typo in positionsCharData

File: src/client/src/ui/analytics/views/chart/analyticsBarChart.jsx [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+    return (
+      <div>{bars}</div>
+    );
+  }
+
+  _createBars(){
+    let propName = CurrencyPairPosition.basePnlName;
+    let chartData = this.props.series;
+
+    let baseVals = _.map(chartData, propName);
```
Comment (fdore) [inline src/client/src/ui/analytics/views/chart/analyticsBarChart.jsx]: rename to baseValues

File: src/client/src/ui/analytics/views/chart/analyticsBarChart.jsx [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+    let maxVal = _.max(baseVals);
+    let minVal = _.min(baseVals);
+
```
Comment (fdore) [inline src/client/src/ui/analytics/views/chart/analyticsBarChart.jsx]: rename to maxValue and minValue

File: src/client/src/ui/analytics/views/chart/pnlBar.jsx [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+    let amount = numeral(this.props.model.basePnl).format('0a').toUpperCase();
+    let amountHover = numeral(this.props.model.basePnl).format('0,0');
+    let labelText = `(${amount}) ${this.props.model.symbol}`;
+
+    let approxLabelWidth = labelText.length * 8;
+    let offset = this._calculateOffset() || -(approxLabelWidth/2);
+    let posStyle = {'left': offset};
+
+    return (
+      <span ref='lbl' className='analytics__barchart-label' style={posStyle}>
```
Comment (fdore) [inline src/client/src/ui/analytics/views/chart/pnlBar.jsx]: rename to label

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 6]
```diff
@@ -0,0 +1,166 @@
+import _ from 'lodash';
+import d3 from 'd3';
+import numeral from 'numeral';
+import {  CurrencyPairPosition } from '../../../../services/model';
+
+export function getPositionsDataFromSeries(series):Array<{symbol:string, baseAmount:number}>{
+  let baseAmtPropName = CurrencyPairPosition.baseTradedAmountName;
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: rename to baseAmountPropertyName

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+
+  let positionData = getPositionsDataFromSeries(props.data);
+
+  let baseVals = _.map(positionData, (val) => {
+    return Math.abs(val[CurrencyPairPosition.baseTradedAmountName]);
+  });
+
+  let maxVal = _.max(baseVals);
+  let minVal = _.min(baseVals);
+
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: rename to baseValues, maxValue, minValue

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 8]
```diff
@@ -0,0 +1,166 @@
...
+  return scales;
+}
+
+
+export function updateNodes(nodeGroup, nodes, scales){
+  let nodeMap = {};
+
+  nodeGroup.each(collide(.1, nodes, scales.r))
+    .attr({
+      transform: function(d, i) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: user arrow function

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 9]
```diff
@@ -0,0 +1,166 @@
...
+        if ( d.x !== undefined && d.y !== undefined && !isNaN(d.x) && !isNaN(d.y)){
+          nodeMap[d.id] = {x: d.x, y: d.y};
+          return 'translate(' + d.x + ',' + d.y + ')';
+        }else{
+          nodeMap[d.id] = {x: 0, y: 0};
+          return 'translate(0, 0)';
+        }
+
+      },
+      id: function(d, i) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: arrow function

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 10]
```diff
@@ -0,0 +1,166 @@
...
+        return d.id;
+      }
+    });
+
+  for (let i = 0; i < nodes.length; i++){
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: use nodes.forEach

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 11]
```diff
@@ -0,0 +1,166 @@
...
+      .on('mouseover', function(d){
+        d3.select(this).style('fill', '#00A8CC');
+      })
+      .on('mouseout', function(d){
+        d3.select(this).style('fill', d.color);
+      })
+      .transition()
+      .duration(duration)
+      .attr({
+        r: function(d) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: arrow function

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 12]
```diff
@@ -0,0 +1,166 @@
...
+          return d.r;
+        }
+      })
+      .style({
+        fill: function(d) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: arrow function

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 13]
```diff
@@ -0,0 +1,166 @@
...
+      });
+}
+
+export function drawLabels(nodeGroup){
+    nodeGroup.attr({
+      x: 0,
+      y: 3,
+      class: 'analytics__positions-label'
+    })
+    .text(function(d) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: d => d.id

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 14]
```diff
@@ -0,0 +1,166 @@
...
+    return numeral(positionsData[index].baseTradedAmount).format('0,0');
+  }
+  return '';
+}
+
+export function collide(alpha, nodes, scale) {
+  let quadtree = d3.geom.quadtree(nodes);
+  let padding = 10;
+
+  return function(d) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: arrow function

File: src/client/src/ui/analytics/views/positions-chart/chartUtil.js [hunk 15]
```diff
@@ -0,0 +1,166 @@
...
+    let r = d.r + 10 + padding;
+
+    let nx1 = d.x - r;
+    let nx2 = d.x + r;
+    let ny1 = d.y - r;
+    let ny2 = d.y + r;
+
+    return quadtree.visit(function(quad, x1, y1, x2, y2) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/chartUtil.js]: arrow function

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 16]
```diff
@@ -0,0 +1,219 @@
...
+    let existingPositionsData = this.state.prevPositionsData;
+    let nodesChanged = positionsData.length !== existingPositionsData.length;
+
+    if (nodesChanged){
+      this.setState({updateRequired: true});
+    }
+    return nodesChanged;
+  }
+
+  _isUpdateRequired(nextProps = this.props){
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: function name misleading...

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 17]
```diff
@@ -0,0 +1,219 @@
...
+    if (this.state.nodes.length === 0 && nextProps.data.length > 0){
+      this._updateNodes(nextProps.data);
+    }
+
+    let positionsData = getPositionsDataFromSeries(nextProps.data);
+    let existingPositionsData = this.state.prevPositionsData;
+    let nodesChanged = positionsData.length !== existingPositionsData.length;
+
+    if (nodesChanged){
+      this.setState({updateRequired: true});
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: should move that call outside of the function

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 18]
```diff
@@ -0,0 +1,219 @@
...
+    }
+    return nodesChanged;
+  }
+
+  _isUpdateRequired(nextProps = this.props){
+    let positionsData = getPositionsDataFromSeries(nextProps.data);
+    let existingPositionsData = this.state.prevPositionsData;
+
+    //positions data has changed on the existing nodes
+    let modifiedData = _.reduce(positionsData, function(result, value, key) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: arrow function

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 19]
```diff
@@ -0,0 +1,219 @@
...
+      return _.isEqual(value, existingPositionsData[key]) ?
+        result : result.concat(key);
+    }, []);
+
+    let stalePositions = _.filter(existingPositionsData, (existingPos) => _.findIndex(positionsData, (pos) => pos.symbol === existingPos.symbol) === -1);
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: would rather do a _.map and then filter, instead of doing a findIndex for each pos

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 20]
```diff
@@ -0,0 +1,219 @@
...
+
+    return modifiedData.length > 0 || stalePositions.length > 0;
+  }
+
+  _updateNodes(data){
+    let nodes = this.state.nodes;
+    let colours = ['#6db910', '#d90a0a'];
+    let positionsData = getPositionsDataFromSeries(data);
+
+    for (let i = 0; i <positionsData.length; i++) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: would rather use _.map

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 21]
```diff
@@ -0,0 +1,219 @@
...
+    if (this.tooltipGroup) this.tooltipGroup.hide();
+    this.setState({updateRequired: true});
+    this._createChartForce(nextProps);
+  }
+
+  _createChartForce(nextProps = this.props){
+    let dom = ReactDOM.findDOMNode(this);
+    this.scales = createScales(nextProps);
+
+    const tick = (e)=> {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: missing space

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 22]
```diff
@@ -0,0 +1,219 @@
...
+    })
+      .attr('class', 'analytics__positions-tooltip').direction('s').offset([-5, 0]);
+
+    svg.call(this.tooltipGroup);
+
+    this.force = d3.layout.force()
+        .nodes(this.state.nodes)
+        .links([])
+        .size([this.props.containerWidth, this.props.containerHeight])
+        .charge(function(d) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: arrow function

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 23]
```diff
@@ -0,0 +1,219 @@
...
+  _update(nodes){
+    if (!nodes || !this.force) return;
+    if (!this.state.updateRequired) return;
+    this.setState({updateRequired: false});
+
+    let dom = ReactDOM.findDOMNode(this);
+    let svg = d3.select(dom).select('svg');
+
+    let nodeGroup = svg.selectAll('g.node')
+      .data(nodes, function(d, i) {
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: arrow function

File: src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js [hunk 24]
```diff
@@ -98,25 +96,27 @@ export default class PositionsBubbleChart extends React.Component{
...
-        nodes.push({
+        let newNode = {
           id: dataObj.symbol,
           r: getRadius(dataObj, this.scales),
-          cx: this.scales.x(i),
+          cx: this.scales.x(index),
           color: color
-        });
+        };
+        nodes.push(newNode);
```
Comment (fdore) [inline src/client/src/ui/analytics/views/positions-chart/positionsBubbleChart.js]: shouldnt push to nodes
